name : first workflow 
on :
  workflow_dispatch :
    inputs :
      environment :
        description : " enter environment name "
        required : true
        default : "staging "
  schedule : 
    - cron : "0 9 * * *"
  pull_request : 
jobs :
  hello :
    runs-on : ubuntu-latest
    steps :
      - name : say-hello
        run : echo "hello from github action"

      - name : print working directory 
        run : echo " ${environment} "

      - name : print host related details 
        run : hostnamectl 

      - name : print os related details
        run : cat /etc/os-release 


    
