name : first workflow 
on :
  schedule : 
  - cron : "0 9 * * *"

jobs :
  hello :
    runs-on : ubuntu-latest
    steps :
      - name : say-hello
        run : echo "hello from github action"

      - name : print working directory 
        run : pwd

      - name : print host related details 
        run : hostnamectl 

      - name : print os related details
        run : cat /etc/os-release 


    
